### ISSUE TITLE
Lightning PayJoin Capabilities Tracking Issue

### ISSUE THREAD

**Issue by DanGould** [chaincase-app/loin#6]
# Chaincase Lightning PayJoin Roadmap

We had a JoinMarket roadmap and pivoted based on what our users wanted. Let's define *exactly* what that means

## ☑ Proof of Concept

Our PoC(s) already exists. We can open a scheduled channel via lightning interaction (loptos). We can host payjoin receiving server from iOS. Epic [channel funding](https://blockstream.info/testnet/tx/78b43450afebbda00520d6adf489c57faf69ecb9e53508ae1d45897be37011d7).

- [x] PoC [article](https://chaincase.app/words/lightning-payjoin)

##   ☐ Alpha: Minimum Viable P2EP

**Think of the utility of Pay-to-Endpoint first**.  PayJoin is CoinJoin functionality built on top of the P2EP interaction.

The minimum quantum of usefulness we can reliably deliver seems to be channel opens from BTCPayServer's internal wallet to their Lightning LND/CLN node. I think [Voltage(https://voltage.cloud/)] is the most popular way to do LN. Say a merchant made some bitcoins and wants to cash out KYC-free to thebitcoincompany.com's lightning only visa cards. They have to open a channel. [Users ask for it](https://twitter.com/GodSaysHodl/status/1549089051730358272)

Typically, they'd move funds from BTCPay On-Chain -> LND On Chain ->, request their LN peer's channel ID, then Open a channel to them. Instead, the first step can be asking that peer for a channel ID, Queueing a channel open to them, and then spend funds directly from BTCPay On-Chain to LND Channel.

This seems to me to be the minimum stable quantum of value we can offer even before privacy preserving. It's strictly better than the first flow. **I especially think e.g. Cash app will be interested in this because it's purely p2p and already in rust**

- [x] CLI interface
- [x] a package / name that Chaincase ships
  - [x] LND Setup ("loptos")
  - [x] Depends on github.com/kixunil/payjoin
- [ ] 90% crash-free PayJoin Receiver: error handling and fallbacks in payjoin receiver
  - [ ] end to end integration test payjoin library https://github.com/Kixunil/payjoin/pull/29
  - [x] smoke test lightning receiver
  - [x] update to rust-bitcoin v0.28.1
- [ ] a video demo
- [x] a demo article [README](https://github.com/chaincase-app/loin/pull/3)
- [x] open channel from wasabi send
- [x] open channel from btcpayserver send
- [x] open channel from LND with PayJoin receive

##  ☐ Beta PayJoin: We're preserving privacy now

Because the above alpha protocol is input substitution only and has no regard for receiver coin selection it's simple to deploy. However, CoinJoin has the added benefit of defeating common input ownership heuristic

- [x] usable channel open scheduling GUI
- [ ] 90% crash-free LND & PayJoin Receiver: error handling and fallbacks for lightning failures
- [ ] Getting Started Guide: Get receiver running on lightning node in < 20 minutes
   - [ ] port forwarding is the hitch here. use existing Onion? Umbrel app?
- [ ] receiver coin selection (manual or automatic)
    - [ ] Avoid unnecessary input heuristic 1 [joinmarket discussion](https://gist.github.com/AdamISZ/4551b947789d3216bacfcb7af25e029e), [GKJSW '21 UIH & PayJoin paper](https://eprint.iacr.org/2022/589.pdf)
    - [ ] Avoid UIH2. Employ output splitting perhaps https://github.com/chaincase-app/wiki/pull/13
- [ ] open channel from CLN with PayJoin receive
- [ ] open channel from sparrow wallet sender
- [ ] open channel joinmarket sender
- [ ] open channel from coldcard via ckbunker sender
- [ ] open channel from sideshift.ai sender
- [ ] open channel from bluewallet sender
- [ ] stretch: fee to get outside Chaincase inputs to avoid UIH via 3rd payjoin participant 

##  ☐ Production Batching Beast: ship with btcpayserver, umbrel, passport, blue wallet receiver

- [ ] Delightful channel opening scheduler GUI
- [ ] Receiver running on lightning node in < 5 minutes
- [ ] Stretch: Integrated GUI: Ride the Lightning, ThunderHub, an externally connected Lightning GUI (Zeus, Zap, Spark, etc) supports us

After we have complete spec support thoroughly tested we will release into the stores without any beta label. Increments from here will continue to be driven from user feedback.
